# SPDX-FileCopyrightText: Copyright (c) NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "llm-api-gateway_lib",
    srcs = ["main.go"],
    importpath = "github.com/NVIDIA/nvcf/src/invocation-plane-services/llm-gateway/cmd/llm-api-gateway",
    visibility = ["//visibility:private"],
    deps = [
        "//src/invocation-plane-services/llm-api-gateway/callerkeys",
        "//src/invocation-plane-services/llm-api-gateway/config",
        "//src/invocation-plane-services/llm-api-gateway/nvcf",
        "//src/invocation-plane-services/llm-api-gateway/provider",
        "//src/invocation-plane-services/llm-api-gateway/server",
        "//src/invocation-plane-services/llm-api-gateway/telemetry",
        "@com_github_rs_zerolog//log",
    ],
)

go_binary(
    name = "llm-api-gateway",
    embed = [":llm-api-gateway_lib"],
    visibility = ["//visibility:public"],
    x_defs = {
        "github.com/NVIDIA/nvcf/src/libraries/go/lib/pkg/version.Service": "nvcf-llm-api-gateway",
        "github.com/NVIDIA/nvcf/src/libraries/go/lib/pkg/version.Version": "{STABLE_VERSION}",
        "github.com/NVIDIA/nvcf/src/libraries/go/lib/pkg/version.GitHash": "{STABLE_GIT_COMMIT_FULL}",
    },
)
