# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
{{- if .Values.enabled }}
{{- if .Values.grafana.adminPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.grafana.adminSecret }}
type: Opaque
stringData:
  admin-user: admin
  admin-password: {{ .Values.grafana.adminPassword | quote }}
---
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-grafana
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Demo metrics
        uid: demo-metrics
        type: prometheus
        access: proxy
        url: http://{{ .Release.Name }}-victoria-metrics:8428
        isDefault: true
        editable: false
        jsonData:
          timeInterval: {{ .Values.scrapeInterval | quote }}
  dashboard.yaml: |
    apiVersion: 1
    providers:
      - name: demo
        type: file
        disableDeletion: true
        allowUiUpdates: false
        options:
          path: /var/lib/grafana/dashboards
  dashboard.json: |
{{ .Files.Get "files/dashboard.json" | indent 4 }}
{{- end }}
